spring.application.name=teamproject


spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug


spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:h2:tcp://localhost/~/board
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
