# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

<<<<<<< HEAD
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Datasource
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=admin
spring.datasource.password=
=======
# Datasource
spring.datasource.url=jdbc:h2:tcp://localhost/~/8mile
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
>>>>>>> 97111923b44f1f865c16d0a125c06ed9ae9c52e2

## Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
<<<<<<< HEAD

## thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

=======
spring.jpa.hibernate.ddl-auto=create
## thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false
>>>>>>> 97111923b44f1f865c16d0a125c06ed9ae9c52e2
