# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Datasource
spring.datasource.url=jdbc:h2:tcp://localhost/~/8mile
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

## Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create


## thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.cache=false

## multipart
spring.servlet.multipart.max-file-size=5MB

## security
logging.level.org.springframework.security=DEBUG
#spring.security.user.name=user
#spring.security.user.password=1234

#google login, redis
spring.profiles.active=oauth, redis

#cookie
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.max-age=3600

#File dir
file.dir=C:/upload/commentFiles/

server.servlet.session.cookie.http-only=false
server.servlet.session.cookie.secure=true